### ISSUE TITLE
Adding sourcemap to the SCSS should be optional

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-dev-compiler#47]
It should be possible to enable/disable soucemap in the CSS file. They contain absolute paths which can be published in not minified distributions.

```css
/**
 * Returns a spacing value with units for given name.
 *
 * @access public
 * @param {String} $spacing [ 'standard' ] - Spacing level.
 * @return {String}
 * @see $ck-def-spacing
 * @see $ck-def-spacings
 */
/* line 4, /Users/pjasiun/workspace/ckeditor5/ckeditor5-theme-lark/theme/helpers/_states.scss */
.ck-hidden {
  display: none;
}
// ...
```
